---
title: 'Grading Grown-ups'
author: ''
summary: 'Using Self-Assessments to Motivate Learning with R'
date: '2018-03-12'
draft: TRUE
slug: self-assessments
categories: []
tags: []
---

- Elaborative interrogation

- Self-explanation

- Resources
    - http://www.indiana.edu/~pcl/rgoldsto/courses/dunloskyimprovinglearning.pdf
    - http://tguilfoyle.cmswiki.wikispaces.net/file/view/What_works,_What_doesn%27t.pdf

- My students wanted grades! I tried one year to use a qualitative grading scale, which resulted in mutiny. May be fine for some programs, and seemed to be OK for Ph.D. students (who don't really care about grades in my experience) but was not OK for masters students. Why not? Possibly because many of my students are adult learners who have had jobs and are returning to school for another degree. They want to know how they are doing, and grades are typically a good way to gauge this!

Logistics:

If knitted PDFs, do self-evaluation in different colors: 

`Roses are \textcolor{red}{red}, violets are \textcolor{blue}{blue}.`

renders: Roses are \textcolor{red}{red}, violets are \textcolor{blue}{blue}.

Roses are <span style="color:red">red</span>, 
violets are <span style="color:blue">blue</span>.

# Homework

A total of 4 homeworks will be assigned; your lowest score will be dropped at the end of the quarter. Some homeworks will require you to use R to analyze data. Although no prior R experience is required for this course, be prepared to do *a lot* of self-guided learning. Students are expected to run R on their own computer or a computer they have plenty of access to and control over. Please attempt to do all homeworks on your own, but you may work with other students. However, you may not submit homework assignments as a group. You should submit your own original work. Please bear in mind that when a homework involves R, you will lose points for any of the following:

* Printing entire dataframes in the R Markdown file
* Code with no comments
* Code which produces an error message

You will have 1 week to complete each homework assignment, and your initial solutions must be submitted to Sakai by 2pm on the due date (at the start of class on Thursdays). Late homeworks will not be accepted. 

## Homework self-assessment

After the initial solutions are due, you will be provided a solution key. Using that key, you will be asked to assess your own initial solutions for accuracy and thoroughness; where you made mistakes, you must discuss and analyze where you went wrong, and correct them without copying/pasting directly from the key (this typically means that you need to include more narrative than we provide in the key). A good self-assessment will include:

- Assessment of the accuracy and completeness of your "initial solutions"
- Correct worked solutions with some discussion and analysis of why your initial solution was incorrect, and reflection on the source of your confusion (if you got an answer correct, this is not necessary)
- Attributions as appropriate to other students who helped you, or other sources such as lecture notes, readings, online resources, etc. that helped you 

## Homework grades

Homework grades will be based on:

- Was your initial solution a good faith effort?
- Did you catch all of your own errors in your self-assessment?
- Is your updated solution correct?

Each homework includes 3 questions, worth 5 points per question, scored as follows:

2 points for each initial solution being “in-good-faith”.

- 2 (Strong attempt): answer reflects strong independent problem solving, with clearly thought out attempts to approach the problem and a diligent and honest effort to find the solution

- 1 (Weak attempt): answer reflects some attempt to approach the problem, but approach appears to be superficial and lacks depth of analysis 

- 0 (No attempt)
    

3 points for the quality of the final answer / discussion.

- 3 (Exceptional): answer is thorough, concise, and clearly demonstrates ability to analyze and interpret statistics as well as theoretical understanding of statistical concepts

- 2 (Adequate): answer addresses the question with moderate inaccuracies in analysis and/or interpretation, or offers a correct but incomplete answer

- 1 (Inadequate): answer attempts to address question with substantial inaccuracies in analysis and/or interpretation

- 0 (Insufficient): answer does not attempt to address question or answer is insufficient to grade
    
This means that:

* You can get 100% of the points if you either:
    - Submit perfectly accurate initial solutions, or
    - Submit a perfectly accurate self-assessment, 
* If you simply cannot submit any homework solutions on time, after the homework due date, you will receive the solutions key and can submit a self-assessment for a max score of 60% (3 out of 5 points per problem). We feel this is fair given that:
    - You did not attempt a good faith effort, and 
    - We will drop your lowest homework grade. 

## What is a "good faith effort"?

Simply submitting nonsense or saying “I can’t do this” for each problem will not meet our criteria for a good faith effort, because there is no attempt on your part to show us why you are struggling, what you tried but didn’t work, what specific part of the problem you got stuck on, which other examples in the text/lecture you tried to work through to get a grasp on the problem, etc. ^[This is especially true if you don’t attend any office hours, post on Sakai, or otherwise seek out help *before* the due date.] The good faith effort is just that- we are interested in seeing evidence of a diligent and honest effort on your part, made with deliberate intention, to understand the problem and attempt an answer.
